@echo off
echo 🤖 Starting Backend with Gemini API...
echo Setting Gemini API Key...
set GEMINI_API_KEY=AIzaSyDwtJr0pj_oSWyiWON7EGEvZt0UmN-9QSI
echo ✅ API Key set!
echo Starting FastAPI backend...
python backend_api.py
